kind: pipeline
type: exec
name: Build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Build
  commands:
  - nix-build -v
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
- name: Notify
  commands:
  - nix run '.#announce-drone'
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
    TOKEN:
      from_secret: irc_token
