kind: pipeline
type: exec
name: Build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Build
  commands:
  - echo "disabled"
  # - nix-build -v
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
- name: Notify
  commands:
  - nix run '.#announce-drone'
  # - " -X POST --data '{{.}}' -H \"Token: $TOKEN\""
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
    TOKEN:
      from_secret: irc_token
# - name: Run Go tests
#   commands:
#   - go test
