kind: pipeline
type: exec
name: Build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Build
  commands:
  - nix-build
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
- name: Notify
  commands:
  - curl localhost:8989/webhook --header "Content-Type: application/json" --request POST --data '{"repo":"test"}' -H "Token: $TOKEN"
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
    TOKEN:
      from_secret: irc_token
# - name: Run Go tests
#   commands:
#   - go test
