kind: pipeline
type: exec
name: Build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Build
  commands:
  - nix-build
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
# - name: Run Go tests
#   commands:
#   - go test
